### ISSUE TITLE
Pullrequest comments

### ISSUE THREAD

**Issue by tomasbjerre** [cdancy/bitbucket-rest#11]
I need POST and GET and for individual comments I need DELETE.

I can work on this one.

**Comment by cdancy** [comment]
@tomasbjerre thanks! I was actually going to tackle this next as I have need to post comments. Ping me if you have any questions about how to do so. This library is modeled around a typical jclouds project so if you don't have any experience/knowledge coding for such a thing it can be a bit daunting until you get used to how everything is wired together.

**Comment by tomasbjerre** [comment]
I started fiddling with this a bit. How do you run the test cases? I do ***gradlew build*** and I get zero tests run. According to test report in ***/build/reports/tests/index.html***.

**Comment by cdancy** [comment]
There are 2 types of tests/tasks: Mock (`mockTest`) and Integration (`integTest`). The former is to model the interaction and ensure the library works as expected while the latter ensures the interaction with bitbucket works as expected. To run either from the command line: `./gradlew mockTest` or `./gradlew integTest` which depends on mock tests running successfully.

It should be noted that for integration tests I make no attempt at setting up a bitbucket server or initing a repo/project/branch/etc, this needs to be done. Open up any of the "Integration*.java" files and you can see how I've hard-coded names of previously existing projects/repos/etc near the top.

Furthermore there are a couple properties `testBitbucketEndpoint` and `testBitbucketCredential` which the integration tests will use to connect to a given bitbucket instance. If you just want to test a single integration test pop open the build.gradle file, navigate to `integTest`, and hard-code in what you need for the moment.

**Comment by cdancy** [comment]
Closing issue as the `CommentsApi` has been implemented with PR's #17 and #16. Endpoints `comment`, `createComment`, `get`, and `delete` have all been coded. Functionality can be found in version `0.0.10` of this library.
