### ISSUE TITLE
Update com.google.code.gson:gson to 2.8.1

### ISSUE THREAD

**Issue by bokc** [cdancy/bitbucket-rest#111]
I use bitbucket-rest on a Spring-boot application. This one use 2.8.1 gson version.

**Comment by cdancy** [comment]
Hmmmm ... Not sure if it'll work correctly. I build on top of the jclouds framework and there may be some issues but I'm honestly not sure. Care to send in a PR?

**Comment by bokc** [comment]
I don't make the update. For the moment I don't use gson with Spring-boot so the 2.5 is running.

**Comment by cdancy** [comment]
Is there an actual issue then or you'd just like to bump gson? If there are classpath issues you can always use the `all` classifier version of this lib which will shade the gson classes.

**Comment by bokc** [comment]
No issue for the moment. Just an improvement for the future
