### ISSUE TITLE
Not able to get list of file

### ISSUE THREAD

**Issue by bokc** [cdancy/bitbucket-rest#112]
I try to get list of file in a branch but it return empty list.
I try rest request with curl and get good file list. 

It's there a way to get the query made by bitbucket-rest api?

**Comment by bokc** [comment]
I find the solution. Add this in logback.xml :

```
    <logger name="jclouds.wire">
        <level value="DEBUG" />
        <appender-ref ref="STDOUT" />
    </logger>

    <logger name="jclouds.headers">
        <level value="DEBUG" />
        <appender-ref ref="STDOUT" />
    </logger>
```

**Comment by cdancy** [comment]
Exactly. What was ultimately your issue?

**Comment by bokc** [comment]
2 issues. First one : wrong repo name. Second one, the LinePage structure is not good when use of FileApi.listLines So I create new api for use files rest entrypoint (https://developer.atlassian.com/static/rest/bitbucket-server/5.4.0/bitbucket-rest.html#idm140014935596976)

**Comment by cdancy** [comment]
@bokc using this library or calling into some other way? We can certainly add an endpoint to accomadate this as going back and forth between 2 different impls has to be a pain :)

**Comment by bokc** [comment]
I I use your lib but adding a FilesApi :-)
