### ISSUE TITLE
Personal access tokens

### ISSUE THREAD

**Issue by martinda** [cdancy/bitbucket-rest#121]
Hello! What do you think about adding the [personal access tokens](https://confluence.atlassian.com/bitbucketserver055/personal-access-tokens-940682155.html?utm_campaign=in-app-help&utm_medium=in-app-help&utm_source=stash#Personalaccesstokens-usingpersonalaccesstokens%22) feature for authentication? If you give me some guidance, I can probably code it myself and open a pull-request. Thanks!

**Comment by cdancy** [comment]
@martinda this has been on my personal backlog for sometime to knock out. It shouldn't be too bad as I do this with my other project `artifactory-rest` and think we [could adopt that approach](https://github.com/cdancy/artifactory-rest/blob/master/src/main/java/com/cdancy/artifactory/rest/filters/ArtifactoryAuthentication.java) here. The file in question you want to [focus on is here](https://github.com/cdancy/bitbucket-rest/blob/master/src/main/java/com/cdancy/bitbucket/rest/filters/BitbucketAuthentication.java). Let me know if you have any questions one way or another.

**Comment by cdancy** [comment]
Closing issue as this functionality has been merged to master and is in the latest `2.0.0` release.
