### ISSUE TITLE
Authenticate with Personal Token

### ISSUE THREAD

**Issue by vanlooverenkoen** [cdancy/bitbucket-rest#127]
Hi,
I want to use your new release to plug into a gradle plugin.  We need to use the Personal Tokens. This is the documentation of the previous release. https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html

This picture is the Bitbucket UI at this point. Is the 'App passwords' the correct section?

![image](https://user-images.githubusercontent.com/21172855/35226653-47512d60-ff8c-11e7-8215-01dc02843939.png)

**Comment by cdancy** [comment]
This would be the documentation you're looking for:

https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html#Personalaccesstokens-Generatingpersonalaccesstokens
