### ISSUE TITLE
RepositoryApi: implement methods to read/update hook settings

### ISSUE THREAD

**Issue by pheck** [cdancy/bitbucket-rest#130]
In order to access a hook's settings, `GET `and `PUT `methods for endpoint `/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/settings/hooks/{hookKey}/settings` should be implemented.
([Bitbucket REST docs](https://docs.atlassian.com/bitbucket-server/rest/5.0.1/bitbucket-rest.html#idm45993794444512))

I might have missed something, but after playing around a bit with the available RepositoryApi-methods, I could only enable/disable a hook, but found no way to configure it.

In my case, I need to enable + configure a "Bitbucket-to-Jenkins" hook for ~75+ repositories.
Of course the configuration options for each hook are different, but supplying them as custom key:value map or similar should allow a generic method that works for any hook.

**Comment by cdancy** [comment]
@pheck you're right in that currently we only have implemented `listHooks`, `getHook`, `enableHook`, and `disableHook`. We would need a follow up endpoint possibly named `modifyHook` that, as you say and I agree with, takes in `Map<String, String>` to pass along. The documentation is not exactly clear on how to implement this though my hunch is that this must be in the the body of the `PUT` request.

Did you want to give things a go or looking for one of us to take on the work?

**Comment by pheck** [comment]
@cdancy given my basic knowledge of java and lack of experience with the frameworks involved in bitbucket-rest, I'd appreciate if one of you could take this on their agenda.

From my `curl`ing with the bitbucket API, I can confirm your guess: `put`ting a json with the appropriate keys/values for each of the hooks to [..]hooks/{hookKey}/settings worked for me.
I don't have a full example at hand as I have no access to the environment right now.

**Comment by cdancy** [comment]
@pheck fair enough. Let me see what I can put together this weekend. Stay tuned...

**Comment by cdancy** [comment]
@pheck can you send over an example of a hook that has settings on your end? We have many hooks here but they all return null/empty json when querying for their settings. I could move forward with the examples provided by Atlassian in the docs but I'd like to have some real world examples of what to expect.

**Comment by pheck** [comment]
@cdancy Sure, I'll get back to you with an example, but I won't have access to the environment I need before monday.

I'm not 100% sure anymore, but I think I saw the same querying behaviour that you describe,
until I changed all the available options for a hook to their non-default values. (i.e. flipping checkboxes, entering dummy values into empty textboxes etc.)
Only then it returned a useful json with keys/values of all of the hook's individual settings.

Did the hooks you queried have any settings other than their defaults?

**Comment by cdancy** [comment]
@pheck care to checkout the above branch/PullRequest and build the project locally and give things a go? I've added the endpoints `RepositoryApi.getHookSettings` and `RepositoryApi.updateHookSettings` both of which take a `HookSettings` object. The object itself can be passed in a `Map` or a `JsonElement` representing the settings to update. 

I was able to find a hook here and update without issue but if you can give things another go, and see if there are any corner cases, that would be great. Let me know what you find.

**Comment by pheck** [comment]
@cdancy That's great! I'm on it, stay tuned for the results...

**Comment by pheck** [comment]
@cdancy Played around for awhile with the new snapshot: it works like a charm!

Putting a json with the required fields for the hook yields the expected results,
on the other hand, `errors()` correctly tells what's going on if I either enter an invalid project/repo/hookkey, or don't include fields mandatory for the hook in the json.
Tried with both `Map` and `JsonElement`

Thank you very much for your work!

**Comment by cdancy** [comment]
@pheck great to hear and thanks for testing things out. Going to add a handful of tests and will do a new point release either today or tomorrow.

**Comment by cdancy** [comment]
@pheck change has been merged. A few changes to note:

- All "hook" endpoints have been moved out of `RepositoryApi` and into the `HookApi`
- The `HookSettings` object changed the method `from` to `of` in keeping with jclouds/guava styles of creating objects.

Putting together one more PR as we speak and will release shortly with a new minor version to account for API breakage.

**Comment by cdancy** [comment]
Also ... to get the hook settings you can do `HookApi.settings()` and to update the hook settings you can do `HookApi.update()` both taking the same parameters they did before.

**Comment by pheck** [comment]
@cdancy sounds great! 
Will try how things go with the refactored API once the release is out, but I won't be able to get to it before monday.

**Comment by cdancy** [comment]
`v2.1.0` has been released.
