### ISSUE TITLE
Support tags as list api

### ISSUE THREAD

**Issue by razem-io** [cdancy/bitbucket-rest#132]
Hello,

I am thinking about creating a pull request but perhaps I missed something. Is it currently not possible to retrieve all tags from a repository with bitbucket-rest?

Have a nice day
Julian

**Comment by cdancy** [comment]
@razem-io not implemented yet. I opened #30 to track this but simply haven't gotten around to it. If you want to send in a PR that would be great as I plan on doing another release very soon.

**Comment by cdancy** [comment]
@razem-io the `TagApi` gained endpoint `list`. New version `2.1.0` will be released before the end of the weekend.

**Comment by cdancy** [comment]
`v2.1.0` has been released.
