### ISSUE TITLE
BranchApi => branches/info/{commitId}

### ISSUE THREAD

**Issue by rs0x29A** [cdancy/bitbucket-rest#136]
Hi.

Bitbucket 4.14.3

Please add support:
```@Path("/branch-utils/{jclouds.api-version}/projects/{project}/repos/{repo}/branches/info/{commitId}")```

Example:
```
https://stash.example.com/rest/branch-utils/1.0/projects/HOMJ/repos/webservices/branches/info/a6eef707c99f88a18148a7792e1dce7fcbfc1e14

{"size":1,"limit":25,"isLastPage":true,"values":[{"id":"refs/heads/master","displayId":"master","type":"BRANCH","latestCommit":null,"latestChangeset":null,"isDefault":true}],"start":0}

```

**Comment by cdancy** [comment]
@rs0x29A let me see what I can put together this weekend for you unless you want to give things a go yourself.

Documentation for this endpoint can be found [HERE](https://docs.atlassian.com/DAC/rest/stash/2.12.1/stash-branch-utils-rest.html)

**Comment by cdancy** [comment]
This endpoint `BranchApi.info` will be in the next release which should be available within the next few hours.
