### ISSUE TITLE
Failed to parse Null description in build-status response

### ISSUE THREAD

**Issue by Joni-Lover** [cdancy/bitbucket-rest#142]
Failed to parse Null description in build-status response

### Expected Behavior
When calling **buildStatusApi().status(commit, 1, 100)** and 'commit' has build-status with **null** description I should get correct response such as below:

`
[Status{dateAdded=1525262228566, description=null, key=0982e632-9d99-4f68-93f5-e50c3f6609c7, name=0982e632-9d99-4f68-93f5-e50c3f6609c7, state=FAILED, url=http://URL}]
`

### Current Behavior
The **null** description can't be parsed:

`
SEVERE: Error parsing input: Null description
java.lang.NullPointerException: Null description
	at com.cdancy.bitbucket.rest.domain.build.AutoValue_Status.<init>(AutoValue_Status.java:25)
	at com.cdancy.bitbucket.rest.domain.build.Status.create(Status.java:51)
`

### Context
I am testing for invalid user inputs with pre-creating build-status on 'commit' with null description.

### Steps to Reproduce (for bugs)
```groovy
@Grab(group='com.cdancy', module='bitbucket-rest', version='2.1.2')

import com.cdancy.bitbucket.rest.BitbucketClient

BitbucketClient client = BitbucketClient.builder().build()
println(client.buildStatusApi().status(commit, 1, 100).values())
```

### Your Environment
MacOX command line

**Comment by cdancy** [comment]
Change has been merged to master. Thanks @Joni-Lover

**Comment by Joni-Lover** [comment]
@cdancy Thank you very match !
