### ISSUE TITLE
Add Pull-Request Delete feature

### ISSUE THREAD

**Issue by martinda** [cdancy/bitbucket-rest#153]
### Expected Behavior

I need the REST API to delete pull-requests.

### Current Behavior

The REST API for deleting pull-requests does not exist yet.

### Context

When writing tests for higher level applications, these tests need to create and delete pull-requests.

### Steps to Reproduce (for bugs)

There is no way to reproduce since the feature does not exist.

### Your Environment

Linux, Bitbucket 5.8.1.

**Comment by cdancy** [comment]
Change has been merged to master.
