### ISSUE TITLE
Enable http logging in application

### ISSUE THREAD

**Issue by richabindra** [cdancy/bitbucket-rest#156]
We need to enable http logging to the console in an application using bitbucket-rest to show the interactions with the bitbucket REST endpoint. @martinda enabled the logging in jenkins-rest by exposing modules option in JenkinsClient builder (https://github.com/cdancy/jenkins-rest/issues/9) and we need to have a similar module option in bitbucket-rest.

I have prepared a PR replicating what was done in jenkins-rest. The PR will show up shortly.

**Comment by cdancy** [comment]
@richabindra very awesome and thanks! Looking forward to reviewing.
