### ISSUE TITLE
Question: Is streaming supported?

### ISSUE THREAD

**Issue by tomasbjerre** [cdancy/bitbucket-rest#158]
Does this client support streams?

The docs here: https://docs.atlassian.com/bitbucket-server/rest/5.14.0/bitbucket-rest.html
States:

> This resource is currently not paged. The server will internally apply a hard cap to the streamed lines,

**Comment by cdancy** [comment]
@tomasbjerre streaming/paging is supported in so far as the API/endpoints allow it. With this library you can certainly get a page, and then the next page, and so on and so forth, until there are no pages left but Bitbucket itself determines this on an endpoint-by-endpoint basis and so there is not much anyone can do until they properly support a given endpoint. I've had luck in the past using a given endpoint that says it's currently not paged but has all the paged parameters in place and it works as expected but I chalk this up more to luck and them not updating their documentation which does indeed happen.

**Comment by tomasbjerre** [comment]
Not really sure I understand you here. To me it sounds like paging and streaming are 2 different things. And it sounds like you are say that paging is supported in this client. 

Specifically I'm looking at `/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/commits/{commitId}/diff` and the issue reported here: https://github.com/jenkinsci/violation-comments-to-stash-plugin/issues/60. This issue shows how the response has been `truncated`.

Does this client handle `truncated` responses somehow? I am considering replacing my hacky client with this client and the question is really, would that solve my issue?
