### ISSUE TITLE
Support for project permissions is missing

### ISSUE THREAD

**Issue by kmoco2am** [cdancy/bitbucket-rest#159]
### Expected Behavior
It is possible to manage permissions for the repositories on project level so there should be support for this API on a project.

### Current Behavior
Currently, there is support only for getting/setting permissions on the repository level. Permissions on project level cannot be managed.

### Context
I need to read all permissions affecting access to the repositories so project level permissions are necessary too.

**Comment by cdancy** [comment]
Thanks for the PR @kmoco2am ! Reviewing now...

**Comment by kmoco2am** [comment]
Works perfectly in 2.3.0.
