### ISSUE TITLE
Need WebHook api methods 

### ISSUE THREAD

**Issue by Joni-Lover** [cdancy/bitbucket-rest#161]
Support new WebHook API

https://docs.atlassian.com/bitbucket-server/rest/5.14.1/bitbucket-rest.html#idm45367160975200

**Comment by mronus** [comment]
@cdancy Is there any progress on this subject? Just asking to be able to plan our roadmap for our product.

**Comment by cdancy** [comment]
@mronus the PR you noted just needs tests written to confirm all works as expected. I can try to get around to things this week but most likely won't get to things until the weekend. I see the committer on the PR chimed in but doesn't look like he will be able to circle back around to things anytime soon.

**Comment by cdancy** [comment]
Version `2.5.0` has been released. @Joni-Lover thanks for the work here buddy as the code you did write worked perfectly which made knocking out the live tests a breeze. Actually wish I would have known that as I would have knocked this out 6 months ago :)
