### ISSUE TITLE
Question: Is there a way to get all tasks?

### ISSUE THREAD

**Issue by ftclausen** [cdancy/bitbucket-rest#165]
Firstly, many thanks for this project! 

Looking at the [live tests](https://github.com/cdancy/bitbucket-rest/blob/master/src/test/java/com/cdancy/bitbucket/rest/features/TasksApiLiveTest.java) I don't see an obvious way to get all tasks associated with a PR in one API call. At the moment I am using the Activities Stream to find all tasks but hoping there is a simpler way.

The underlying Bitbucket Server REST API path pattern for this is: `/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/pull-requests/{pullRequestId}/tasks`

**Comment by cdancy** [comment]
This is not currently implemented. Would you be open to submitting a PR for this feature?

**Comment by ftclausen** [comment]
Thanks for your reply. I’m am certainly open to submitting a PR once I return from vacation in 2 weeks.

**Comment by cdancy** [comment]
@ftclausen let me know if you have any questions when you get back and I can walk you through things. If you can't find the time just say so and I can try to whip something together on the weekend. Shouldn't be that bad as it's only 1 endpoint I just personally like to encourage outside contributions.

**Comment by ftclausen** [comment]
Thanks, and I will let you know if I have any questions. Today is actually my last day of work prior to my vacation so did shoot in a [comment fix PR](https://github.com/cdancy/bitbucket-rest/pull/168) that was biting us.

**Comment by cdancy** [comment]
Closing. Feel free to re-open should you want to discuss further.
