### ISSUE TITLE
Parsing error when a comment contains both a task _and_ a like.

### ISSUE THREAD

**Issue by ftclausen** [cdancy/bitbucket-rest#167]
**PR forthcoming** and will update issue once it is submitted. 

### Expected Behavior

Parsing of comment (for example, from the activities page) should return activity page objects to client code.

### Current Behavior

Parsing fails in bitbucket-rest prior to reaching client code. The error looks as follows:

```
    ERROR [2019-01-15 00:21:03,721] org.jclouds.http.functions.ParseJson: Error parsing input: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 141 column 29 path $.values[4].comment.tasks[0].anchor.properties.
    ! java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 141 column 29 path $.values[4].comment.tasks[0].anchor.properties.
    ! at com.google.gson.stream.JsonReader.nextString(JsonReader.java:838)
    ! at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:422)
```

Rest of stack trace omitted.

### Context

I can't parse PRs with liked comments; this is a problem for our development workflow.

### Steps to Reproduce (for bugs)

1. Make a comment
2. Add a task
3. Like the comment

**Comment by cdancy** [comment]
Fixed as per #168
