### ISSUE TITLE
Update pull request when the pull request is in open state

### ISSUE THREAD

**Issue by richabindra** [cdancy/bitbucket-rest#172]
### Expected Behavior
After a pull request has been opened, we can update the pull request's title, description, reviewers or the destination branch.

### Current Behavior
Using the bitbucket-rest PullRequestApi, we can create a new pull request or get the existing pull request's attributes, but we cannot update the title, description, reviewers or the destination branch of an existing pull request.

### Context
We are trying to update the reviewers of an existing pull request currently.

**Comment by cdancy** [comment]
Checkout the `PullRequestApi.*Participant` endpoints and let me know how you make out.

**Comment by richabindra** [comment]
Thanks @cdancy ! I have just started working on this issue and will send a PR for review once done.

**Comment by richabindra** [comment]
@cdancy - a quick question for my clarity pls. Why do I need to checkout the `PullRequestApi.*Participant` endpoints? I thought we have to add a new post method declaration in PullRequestApi class (similar to "pull-request:get") 

https://github.com/cdancy/bitbucket-rest/blob/22a62f633c3432287f054387df69ad498ce72983/src/main/java/com/cdancy/bitbucket/rest/features/PullRequestApi.java#L71-L80

and further add corresponding classes etc.??

**Comment by cdancy** [comment]
Those endpoints are already available in this library you just have to use them :) Check out the below link and you can see they've already been defined.

https://github.com/cdancy/bitbucket-rest/blob/22a62f633c3432287f054387df69ad498ce72983/src/main/java/com/cdancy/bitbucket/rest/features/PullRequestApi.java#L243

**Comment by richabindra** [comment]
But now if I look at the participants api, I think it might solve the purpose of adding the reviewers to the existing pull request. What do you think will be a better approach.?

**Comment by martinda** [comment]
@richabindra there is also a [participants REST API](https://docs.atlassian.com/bitbucket-server/rest/6.0.0/bitbucket-rest.html?utm_source=%2Fstatic%2Frest%2Fbitbucket-server%2Flatest%2Fbitbucket-rest.html&utm_medium=301#idp284).

**Comment by richabindra** [comment]
> Those endpoints are already available in this library you just have to use them :) Check out the below link and you can see they've already been defined.
> 
> [bitbucket-rest/src/main/java/com/cdancy/bitbucket/rest/features/PullRequestApi.java](https://github.com/cdancy/bitbucket-rest/blob/22a62f633c3432287f054387df69ad498ce72983/src/main/java/com/cdancy/bitbucket/rest/features/PullRequestApi.java#L243)
> 
> Line 243 in [22a62f6](/cdancy/bitbucket-rest/commit/22a62f633c3432287f054387df69ad498ce72983)
> 
>  Participants addParticipant(@PathParam("project") String project,

Yes true! Alright, that makes things simpler then :) thanks!

**Comment by cdancy** [comment]
Sounds good. Let me know how things work out.

**Comment by richabindra** [comment]
@cdancy - sure! thanks again :)

**Comment by richabindra** [comment]
@cdancy - the participants api works all good for us :) thanks again for pointing in the right direction.
