### ISSUE TITLE
Implement last-modified API

### ISSUE THREAD

**Issue by adam-tylr** [cdancy/bitbucket-rest#179]
Implement the API described here: https://docs.atlassian.com/bitbucket-server/rest/5.1.0/bitbucket-rest.html#idm45588159014928

This will get a list of files at the path and include their last modified time

I'll submit a PR

**Comment by adam-tylr** [comment]
@cdancy Do you want this in the files API or the commits API? It returns a map of files to their latest commit.

**Comment by cdancy** [comment]
Hey @adam-tylr didn't even see this issue come across my feed. Looking now...

**Comment by cdancy** [comment]
Lets go with the `FileApi` and see how that looks. Seems the most likely place to put things :)

**Comment by adam-tylr** [comment]
Sounds good. Thanks for the quick response!

**Comment by cdancy** [comment]
No problem. I'm currently doing a 24 hour hackathon at my job at the moment so I'll be up all night if you need anything ;)

**Comment by cdancy** [comment]
Closing per #180
