### ISSUE TITLE
RepositoryApi: get all public/private repos together without looping projects

### ISSUE THREAD

**Issue by mronus** [cdancy/bitbucket-rest#190]
RepositoryApi#list throws exception when sending project as null. I know that Bitbucket Rest API supports listing all repos together without looping through all projects one by one.

I couldn't find anything about that, so would like to know if there is a planned roadmap about this or if it already exists, and if the exception thrown by RepositoryApi#list is thrown intentionally or if it is a bug.

One more note, Bitbucket supports creating repositories without associating with a project.

**Comment by cdancy** [comment]
> One more note, Bitbucket supports creating repositories without associating with a project.

@mronus this is true if you're creating a repo under your **user name** if you're not attaching it to a project. The repository has to go somewhere, under some umbrella, so it's not under a project it is assumed you want to put things under your **user name** which essentially acts as a project folder. This client expects you to pass in a projectId (be than an actual projectId or a user-name) and doesn't take any short-cuts one way or another. I suppose it would be possible to allow passing in a null parameter for projectId and then attempt to inject the userName part of your credentials in its place. That doesn't sound like a bad idea. But if you're currently stuck I suggest passing in your username instead of the projectId and you should be good to go.

**Comment by mronus** [comment]
Thanks a lot @cdancy , I got it very well in terms of repos which has no parent project; however, it is still an open question how to use the repos endpoint "/rest/api/1.0/repos". Has it been implemented in the library yet? I checked docs, libs everything but couldn't find anything. So I just want to be sure before starting investigating different solution, or maybe I can create a PR if I can spare time.

**Comment by cdancy** [comment]
@mronus we have loads of endpoints coded for in our [RepositoryApi](https://github.com/cdancy/bitbucket-rest/blob/master/src/main/java/com/cdancy/bitbucket/rest/features/RepositoryApi.java) class.

**Comment by mronus** [comment]
@cdancy I checked it already but I think we have an inconsistency there. We have two Api (ProjectApi and RepositoryApi) classes with the same root path: "@Path("/rest/api/{jclouds.api-version}/projects")" . In terms of resource ownership, I think all endpoints which has {project} parameter in RepositoryApi should have been in [ProjectApi](https://github.com/cdancy/bitbucket-rest/blob/master/src/main/java/com/cdancy/bitbucket/rest/features/ProjectApi.java) . So I think it doesn't seem possible to fetch all repos via single http call instead of http call per project because of this inconsistency. Just a friendly feedback :)

**Comment by mronus** [comment]
I think it will be much better discussing it through a pull request. I'll create it ASAP.

**Comment by cdancy** [comment]
@mronus I'm not sure an entire new Api/Endpoint is necessary as using the `RepositoryApi` class that I noted above should be sufficient. What I think you want to do instead is to make the "project parameter" optional or Nullable. Something similar was done recently on [THIS PR](https://github.com/cdancy/bitbucket-rest/pull/187/files) which you may be able to use and/or take away from.

**Comment by mronus** [comment]
@cdancy I got the resolution for listing repos under username. The thing that I want to point out is listing all repos regardless of project. So I think we need to add the endpoint "/rest/api/1.0/repos" to the RepositoryApi somehow. I created a [PR](https://github.com/cdancy/bitbucket-rest/pull/191/files) as start point. Please review and let me know your thoughts.
