### ISSUE TITLE
Fix incompatibility with Spring due to Gson version

### ISSUE THREAD

**Issue by kstrijbos** [cdancy/bitbucket-rest#194]
### Expected Behavior
It should start without error when Spring Boot is on the classpath.

### Current Behavior
The Jclouds dependency has a dependency on Gson 2.5. Spring Boot has a dependency on Gson 2.8.5. Google made some breaking changes (within a minor...). More specifically: Gson 2.8.5 does not contain a constructor that is used in Jclouds 2.1.2. Vice versa, Gson 2.5 does not contain a method that is used in the autoconfigure module of Spring Boot.

### Context
Trying to create a small application to interrogate our BitBucket.

### Steps to Reproduce (for bugs)
Just put Spring and Jclouds on the classpath.

### Your Environment
Intellij, OSX, Maven.

### Current solution
Manually exclude the GsonConfiguration from the autoconfigure module when declaring a @SpringBootApplication.

**Comment by cdancy** [comment]
This is a known jclouds issue and unfortunately not that easy to solve. You can however get around this problem by specifying the `all` classifier wherever you define the dependency on this library. That will pull in a shaded version of this lib and allow you to then put whatever you want in the path without things getting clobbered. Give that a go and let me know how it works out.

**Comment by kstrijbos** [comment]
Thanks for the answer. In the case of Spring, I believe it's a cleaner solution to explicitly exclude the Configuration class from the classpath scanning.

`@EnableAutoConfiguration(exclude = {org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration.class})
`

**Comment by cdancy** [comment]
That could work as well. Closing this issue as it appears we now have multiple paths forward. Feel free to re-open should you want to discuss things further.
