### ISSUE TITLE
Tag API not deleting tags as expected

### ISSUE THREAD

**Issue by padas2** [cdancy/bitbucket-rest#195]
**Problem :**
TagApi does not delete tags as expected.

**Code used to delete tag :**
`api().tagApi().delete(project, repo, tag)`.
I see the tag still present in the repository.

**Verification :** 
Was able to delete tag by firing a DELETE call to 
`rest/git/1.0/projects/<project-name>/repos/<repo-name>/tags/<tag-name>`
with appropriate credentials.

Am I missing anything here?

**Comment by cdancy** [comment]
@padas2 are there any exceptions thrown? You can check the `RequestStatus` returned to see if any errors were thrown.

**Comment by padas2** [comment]
On printing error objects , this is what I get.
`Error{`
`    context=DELETE <tag-delete-request-url> HTTP/1.1 -> HTTP/1.1 405 null, `
`    message=Failed to parse output: `
`    message=com.cdancy.bitbucket.rest.shaded.com.google.gson.stream.MalformedJsonException: Use `
`                    JsonReader.setLenient(true) to accept malformed JSON at line 1 column 9 path $, `
`    exceptionName=com.cdancy.bitbucket.rest.shaded.com.google.gson.JsonSyntaxException, `
`    conflicted=false, `
`    vetoes=[]`
`}`

I think the method itself is not allowed here.

**Comment by cdancy** [comment]
What is the exact command you used to verify?

How did you build this bitbucket-client? The 405 would suggest you don't have the credentials to delete or it's an older/newer version of  Bitbucket or something. If you enable debug logging, however you are invoking this client, you'll get a lot of more information surrounding the actual http call.

**Comment by cdancy** [comment]
Yeah upgrade to latest and greatest as a lot has changed since then.

How did you verify things work outside of the client? Maybe using curl?

**Comment by padas2** [comment]
A DELETE call using Postman.

**Comment by padas2** [comment]
Whoa that works.
Tag has been deleted now.
I will close the issue now.

**Comment by cdancy** [comment]
Sounds good! You must have hit some bug that existed a while back.

**Comment by padas2** [comment]
Yes, this [commit](https://github.com/cdancy/bitbucket-rest/commit/416c832f77922e79980e52213b7b0b3ae3d72b21) had already fixed the issue .
So we're good. 
It was just a matter of upgrading to the latest version.
