### ISSUE TITLE
[Question] Does this client support both Bitbucket server and cloud? 

### ISSUE THREAD

**Issue by neomatrix369** [cdancy/bitbucket-rest#198]
### Expected Behavior
The examples on the README would work as expected when run against API endpoint https://api.bitbucket.org/2.0/

Also, some log output of sent and received messages i.e. request and response objects - is there a way to enable debug logging?

### Current Behavior
I get an error like: `{"message": "Resource not found", "detail": "There is no API hosted at this URL.\n\nFor information about our API's, please refer to the documentation at: https://developer.atlassian.com/bitbucket/api/2/reference/"}}`

### Context
I was getting started with using your client instead of writing one by hand. And I have supplied the right user name and password. I know this because I passed an incorrect password I would get `PullRequest{errors=[Error{context=Invalid Authorization header,....`.

It's good to see it works with an App password (created via the Bitbucket.org dashboard)

### Your Environment
IntelliJ IDE + Maven

**Comment by cdancy** [comment]
@neomatrix369 yeah it works across the board and just targets the REST endpoints. It should be noted that not ALL endpoints have been coded for just those that are most relevant and/or that users care to see and implement. If there is something that you'd like, that is missing here, just open an ISSUE and ask and either myself or one of the other contributors will chime and see if we can knock things out. OR ... if you want to see things get in quicker you can open a PR yourself and we can review to get things in.

As far enabling debug logging: just enable debug logging through whatever means you're invoking this code and you'll get loads of information piped to stdout. If that's not easy enough you can write or amend an existing `integTest`, point the relevant test properties at your Bitbucket instance, and run the test from the command line and watch all of the http wire logs get printed :)

**Comment by neomatrix369** [comment]
> @neomatrix369 yeah it works across the board and just targets the REST endpoints. It should be noted that not ALL endpoints have been coded for just those that are most relevant and/or that users care to see and implement. If there is something that you'd like, that is missing here, just open an ISSUE and ask and either myself or one of the other contributors will chime and see if we can knock things out. OR ... if you want to see things get in quicker you can open a PR yourself and we can review to get things in.
> 
> As far enabling debug logging: just enable debug logging through whatever means you're invoking this code and you'll get loads of information piped to stdout. If that's not easy enough you can write or amend an existing `integTest`, point the relevant test properties at your Bitbucket instance, and run the test from the command line and watch all of the http wire logs get printed :)

Thanks for the reply, I'm still not sure why the implementation I copied from your example didn't work on the Bitbucket cloud?

Enhancing the library is a great idea and thanks for the invite although there is a bit of a learning curve to get around the internals and how it has been implemented. I'll let you know when I get around that. I have implemented the Bitbucket REST API via UniRest and have written a small class that does that atm. But I will keep my eyes open in this area for future needs. Thanks.

**Comment by cdancy** [comment]
Closing this ISSUE as convo has gone stale. Feel free to re-open if necessary.

**Comment by lukelast** [comment]
Looks like without v2 api support cloud is not going to work.

#203

**Comment by cdancy** [comment]
@lukelast We personally don't use Bitbucket cloud here but if they changed how all the API's work for their `cloud` offering then that would be horrible and would require all projects to change drastically. If however it's a matter of just change the version being used to point elsewhere that's easy enough to do with this library but it appears that may not work perfectly if the aforementioned PR is to believed.
