### ISSUE TITLE
MVN Repository files not found

### ISSUE THREAD

**Issue by AlyIbrahim** [cdancy/bitbucket-rest#201]
### Expected Behavior
Adding the maven dependency to my project and running 
mvn clean install should end up pulling the pom and jar file from maven repositories.

### Current Behavior
```Downloading from central: https://repo.maven.apache.org/maven2/com/cdancy/bitbucket-rest/2.5.3/bitbucket-rest-2.5.3.pom
[WARNING] The POM for com.cdancy:bitbucket-rest:jar:2.5.3 is missing, no dependency information available
Downloading from central: https://repo.maven.apache.org/maven2/com/cdancy/bitbucket-rest/2.5.3/bitbucket-rest-2.5.3.jar
```
And if you follow the link to the jar file, I am getting `404 Not Found`

### Context
I am trying to add bitbucket-rest as a dependency to my project.
I added the following dependency in my pom.xml
```
<dependency>
    <groupId>com.cdancy</groupId>
    <artifactId>bitbucket-rest</artifactId>
    <version>2.5.3</version>
</dependency>
```

### Steps to Reproduce (for bugs)
Create a java maven project
Add this dependency to your pom.xml file:
```
<dependency>
    <groupId>com.cdancy</groupId>
    <artifactId>bitbucket-rest</artifactId>
    <version>2.5.3</version>
</dependency>
```

run `mvn clean install`

### Your Environment
Linux RHEL 7.6
JDK 1.8.0_201
Maven 3.6.0

**Comment by cdancy** [comment]
I actually don't publish to maven and ONLY publish to Bintray. I _assume_ things are getting propagated to maven maybe by Bintray but I never wired that up. Can you try pulling from Bintray and see if that resolves your problem?

**Comment by AlyIbrahim** [comment]
Yep, finally it worked ..
It took me sometime to make it to pull from bintray, maybe it's me having the first time with bintray, but I suggest, we can add this info to the README to make it easier.
I can send a pull request to this ..
Actually it turned me away from few weeks back when I was not able to pull from Maven, but I like the work been done here and give it another try and finally end up opening this issue, but others can miss the chance to use this if they don't have the quick and easy way to make it work.
Thanks Chris

**Comment by cdancy** [comment]
@AlyIbrahim yeah feel free to send in a PR to add to the documentation. I do note that you can resolve things through `jcenter` as that's largely interchangeable with `bintray` assuming folks know this. I've amended the line on the README.

**Comment by AlyIbrahim** [comment]
Got it ..
Just since it took me sometime and ending up with an issue, making it more clear net to maven configuration will make it more handy and easy to reach.
PR is already sent
Thanks again for the support
