### ISSUE TITLE
Support for API v2.0

### ISSUE THREAD

**Issue by AlyIbrahim** [cdancy/bitbucket-rest#203]
### Expected Behavior
With Bitbucket deprecating v1.0 to it's cloud service, the interaction with bitbucket cloud "The online version should be using API v2.0 : https://developer.atlassian.com/bitbucket/api/2/reference/

### Current Behavior
The current library is not usable for bitbucket cloud, and if bitbucket server implemented v2.0 as well, the whole functionality will be useless

### Context
Open discussion on how to implement v2.0 and start adding those new API to the library

**Comment by cdancy** [comment]
No immediate thoughts but I suspect this might need to be done on an endpoint-by-endpoint basis ... _maybe_? Additionally, and if the endpoints largely stay the same just the api version number is increased, then folks can pass in the `jclouds.api-version` as an override and set it to 2.0 as documented [HERE](https://github.com/cdancy/bitbucket-rest#on-overrides). 

We could also do an initial ping of sorts, as part of the library initialization, to check if the 2.0 API is available and if so then programmatically set the version based on that response.

I suspect by deprecating they will keep the existing functionality/URL's in place for sometime before ripping things out.

**Comment by AlyIbrahim** [comment]
@cdancy 
The URLs seems a lot changes, some of the domain objects may be reusable.
I do agree to your point of endpoint-by-endpoint basis.
I guess there is a split now in APIs, for Cloud version they use 2.0, and for Server version they still use v1.0

**Comment by AlyIbrahim** [comment]
@cdancy 
Check the changes in this link:
https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/

**Comment by cdancy** [comment]
Thanks. Yeah that's interesting... I would be game for doing a major version release against `v2.0` only, that would be 3.0 in our world, and all bitbucket-server changes will stay on the 2.x branch.

**Comment by AlyIbrahim** [comment]
I am doing some tests and may help in this 3.0 branch.
Also trying to get more into your coding style using jclouds so I can start rolling.

**Comment by cdancy** [comment]
> Also trying to get more into your coding style using jclouds so I can start rolling.

+1

**Comment by cdancy** [comment]
Closing.. If folks want to re-open to further discuss feel free to do so.
