### ISSUE TITLE
Implement Code Insights API

### ISSUE THREAD

**Issue by hesch** [cdancy/bitbucket-rest#204]
The Code Insights API should be implemented:

https://docs.atlassian.com/bitbucket-server/rest/6.4.0/bitbucket-code-insights-rest.html

**Comment by cdancy** [comment]
Version `2.6.0` has been released. Thanks again @hesch!!!

**Comment by cdancy** [comment]
Just released version `2.6.1` as this contains a bug fix that was applied to one of my other projects wherein there is a classloader leak in the older version of guice that jclouds uses internally. I recommend using this version.
