### ISSUE TITLE
Code Insight API ReportData can have values of different types

### ISSUE THREAD

**Issue by succcubbus** [cdancy/bitbucket-rest#208]
### Expected Behavior
Adding ReportData of DataTypes other than TEXT should work

### Current Behavior
Only adding ReportData of DataType TEXT works, because other types need to be encoded as described here:
https://docs.atlassian.com/bitbucket-server/rest/6.9.0/bitbucket-code-insights-rest.html#idp9
But currently every type is encoded as a string.

### Context
I was trying to add a link to a report.

### Steps to Reproduce (for bugs)
```
val data = InsightReportData.create("Title", InsightReportData.DataType.LINK, "https://example.com/insightReportData");
val report = CreateInsightReport.create("", "https://example.com/buildUrl", null, CreateInsightReport.RESULT.PASS, "", "", List.of(data));
insightsApi.createReport("project", "repo", "commit", "key", report);
```

### Your Environment
Java 11
Jenkins CI

So I already fixed this, but then read that I should create an issue first.
Just tell me if I should open a PR.

**Comment by cdancy** [comment]
@succcubbus if you've got a fix I'll definitely take that PR!
