### ISSUE TITLE
do we have support for diff API

### ISSUE THREAD

**Issue by gopikanthk** [cdancy/bitbucket-rest#210]
Do we have support for diff api for a given pull request?

Ex: ../pull-requests/{PR-ID}/diff

**Comment by cdancy** [comment]
@gopikanthk never wired that up. Would you be up for sending in a PR? Looks easy enough to knock out:

https://docs.atlassian.com/bitbucket-server/rest/5.16.0/bitbucket-rest.html#idm8297336928
