### ISSUE TITLE
Implement project 'hooks' endpoint

### ISSUE THREAD

**Issue by dokaspar** [cdancy/bitbucket-rest#225]
The current hookApi implements various endpoints to manage repository-level hook settings.
However, the project-level hook settings are missing and should also be implemented:
https://docs.atlassian.com/bitbucket-server/rest/7.3.1/bitbucket-rest.html#idp393

**Comment by cdancy** [comment]
@dokaspar hmmm ... we _could_ do something wherein if the `repo` parameter is **null** we could omit that part of the path. Should be easy enough to wire up. Care to send in a PR?

**Comment by cdancy** [comment]
Closing. If someone wants to open a PR or discuss further feel free to do so.
