### ISSUE TITLE
MergeConfigType misses value "PROJECT"

### ISSUE THREAD

**Issue by tanjaem** [cdancy/bitbucket-rest#227]
### Expected Behavior
When a repository has set the merge configuration type to the value "PROJECT", the repositoryApi should successfully retrieve pull request settings with the call com.cdancy.bitbucket.rest.features.RepositoryApi.getPullRequestSettings(String, String).

### Current Behavior
Because the value "PROJECT" is missing in the enumeration com.cdancy.bitbucket.rest.domain.repository.MergeConfig.MergeConfigType, the repositoryAPI call mentioned above throws the following exception:

```
SEVERE: Error parsing input: No enum constant com.cdancy.bitbucket.rest.domain.repository.MergeConfig.MergeConfigType.PROJECT
java.lang.IllegalArgumentException: No enum constant com.cdancy.bitbucket.rest.domain.repository.MergeConfig.MergeConfigType.PROJECT
```

### Context
Please let me know in case you need more context information.

### Steps to Reproduce (for bugs)

Have a project with merge configuration type set to "PROJECT". Then try running the following test:

```
BitbucketClient client = BitbucketClient.builder().endPoint("your-url").token("your.token").build();
// will throw an exception:
PullRequestSettings pullRequestSettings = client.api().repositoryApi().getPullRequestSettings("your-project", "your-repository");
MergeConfigType mergeConfigType = pullRequestSettings.mergeConfig().type();
//assertEquals(MergeConfigType.PROJECT, mergeConfigType);
```

### Your Environment
Let me know in case you need more information here.

**Comment by cdancy** [comment]
@tanjaem `2.6.3` is out now with this fix.
