### ISSUE TITLE
[Question] Is there a way to do client certificate authentication?

### ISSUE THREAD

**Issue by aajimal** [cdancy/bitbucket-rest#248]
Is there a way to pass in a client certificate to be used for authentication?
I see that we can do user/pass or token auth in the example docs and code but was unable to find any place in the code to somehow use client certs as well.

**Comment by cdancy** [comment]
@aajimal I suspect there is through `jclouds` (which is what I used underneath the hood) just never looked into it. If someone from the community wants to give things a go and wire something together I'd be more than happy to take the PR.
