### ISSUE TITLE
JSON deserialization failure

### ISSUE THREAD

**Issue by lmyslinski** [cdancy/bitbucket-rest#249]
### Expected Behavior
The library should parse server response properly.

### Current Behavior
`Failed to parse output: message=com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8 path $`

### Context
Multiple endpoints do not work as expected - Request completes sucessfully but the library does not parse the response properly which results in an exception:

```
Error{context=Error parsing input: null
{statusCode=201 ....  contentType=application/json;charset=UTF-8, expires=null], written=false, isSensitive=false]}, message=Failed to parse output: message=com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8 path $, exceptionName=com.google.gson.JsonSyntaxException, conflicted=false, vetoes=[]}
```

### Steps to Reproduce (for bugs)
Send an createSshRequest. I've encountered this bug also with project creation api.
```
val client = buildClient(endpoint, token)
      val resp = client
        .api()
        .keysApi()
        .createForRepo(
          projectKey,
          repositoryName,
          CreateAccessKey.create(CreateKey.create(sshKey), PermissionType.REPO_WRITE)
        )
``` 

### Your Environment
OpenJDK 15, 
"com.cdancy" % "bitbucket-rest" % "2.7.1",
Bitbucket Server 7.8.0

**Comment by cdancy** [comment]
@lmyslinski this happens when Bitbucket does not return the expected json response. What endpoints do you see this happening on? And could you give examples of what those endpoints are returning in your case?

**Comment by lmyslinski** [comment]
I've tested this on two separate bitbucket instances, one with https and one without. Sample response:
```
{
    "key": {
        "id": 3,
        "text": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUUayjVuFXGqAKA9OPCP/BVdrGl28ieb0C1OGovNpB6n+IFePDt6PkvHLzvJIncdD7T8+Kn5D/4tVe+ckwUzXpn4i9yiI6cs/zVnjqSitGwtlp6RnQzukQZCZxHt18bXXra6L5m8tr7essnotIIDL02oSmKx4aHPqSemgaLHP5VbKjNnLC+XydfBecmHzkIdZwknqnZqsYbESyO25iNftbIwDJtc8pjfAcHL7jgahdHrOnuiwWfR9H2cEr3xJc41iRFLQ2VQaclpO/R27nc+8AEDktPDEwgGC1dBdigEBrWtnlXAdes1T4k+D+ieXtbTfOirVHLycRQ7NjAVTkTh1h",
        "label": ""
    },
    "repository": {
        "slug": "test-repository",
        "id": 13,
        "name": "test-repository",
        "hierarchyId": "2c82a31ae877d31ec888",
        "scmId": "git",
        "state": "AVAILABLE",
        "statusMessage": "Available",
        "forkable": true,
        "project": {
            "key": "ALGTEST",
            "id": 1,
            "name": "Algorithmia Test Project",
            "description": "Project used for integration testing",
            "public": false,
            "type": "NORMAL",
            "links": {
                "self": [
                    {
                        "href": "https://bb.enthalpy.click/projects/ALGTEST"
                    }
                ]
            }
        },
        "public": false,
        "links": {
            "clone": [
                {
                    "href": "https://bb.enthalpy.click/scm/algtest/test-repository.git",
                    "name": "http"
                },
                {
                    "href": "ssh://git@bb.enthalpy.click:7999/algtest/test-repository.git",
                    "name": "ssh"
                }
            ],
            "self": [
                {
                    "href": "https://bb.enthalpy.click/projects/ALGTEST/repos/test-repository/browse"
                }
            ]
        }
    },
    "permission": "REPO_WRITE"
}
```

I'm pretty convinced it's related to Gson and not this specific endpoint - as I've said, this issue occured for me on other endpoints as well. To work around this I've written my own rest api client that works as expected and the bitbucket server always returns a valid json object

**Comment by lmyslinski** [comment]
On my classpath I see Gson `2.8.6`

**Comment by lmyslinski** [comment]
To be more specific, if Bitbucket returns 401 the parses fails too. I've written this piece of code to around it: 
```
private def returnWithErrorHandling[T <: ErrorsHolder](responseObj: T): T = {
    if (responseObj.errors().isEmpty) {
      responseObj
    } else {
      val err = responseObj.errors().get(0)
      if (err.context() != null && err.context().contains("401")) {
        // 401 results in a json parse exception, let's throw something more useful
        throw AuthenticationError(s"Permission denied : 401")
      } else {
        throw BitbucketError(err.message(), err.exceptionName())
      }
    }
  }
```

**Comment by cdancy** [comment]
Closing. If you'd like to discuss further feel free to re-open.

**Comment by SuppenNudel** [comment]
I am encountered this problem right now.
I am using the fileApi; lastModified and updateContent.
I am using this library's version 2.7.2
Our Bitbucket Server is on version v7.17.7
Please let me know if you need more info.

**Comment by SuppenNudel** [comment]
@lmyslinski I've also used a self written implementation using retrofit2 for some other endpoints. But I have difficulties writing for the fileApi because it contains a file upload and I can't seem to get it to work.
Can you provide me with your solution or tell me which framework you use if any?

**Comment by cdancy** [comment]
@SuppenNudel you could try bumping to latest version of `3.0.2`. Do you have a code snippet so I can see what you're doing? Do you have a stracktrace to look at? If you run with "debug enabled", however you're invoking the code, the library itself will dump out the http-wire logs to see what is going sideways.

Also ... it's recommended to use the `all` classifier version of this library so that you don't hit silly clobbering issues with gson/etc.

**Comment by lmyslinski** [comment]
@SuppenNudel This was done in Scala with `Play` and `sttp`: https://gist.github.com/lmyslinski/1420421c7e95141c327f54c831f966c6

**Comment by SuppenNudel** [comment]
Turns out the group id changed since I last updated this library. So I wasn't able to find it XD
But upgrading to 3.0.1 fixed the issue.
3.0.2 seems to be compiled with Java 11. That didn't work in my corp environment, since we are still on Java8.
Thanks for your help!
