### ISSUE TITLE
Missing committer &  committerTimestamp when retrieving commit information

### ISSUE THREAD

**Issue by tjxn** [cdancy/bitbucket-rest#260]
When retrieving commit information with the CommitApi the committer and committer timestamp returned by bitbucket is ignored and not returned.

### Expected Behavior
The Commit object returned should contain the committer and committerTimestamp fields.

### Current Behavior
The Commit object does not contain the committer and committerTimestamp information.

### Context
I'm writing an application to display commit information and need to be able to determine the committer and the commit date which differ from my author and authorTimestamp. 

### Steps to Reproduce (for bugs)
Retrieve any commit

### Your Environment
Bitbucket version: 5.9.2
bitbucket-rest version: 2.7.1

**Comment by cdancy** [comment]
@tjxn version `2.7.2` has been released with this change.
