### ISSUE TITLE
Support for 'unapproveOnUpdate' repository pull request setting

### ISSUE THREAD

**Issue by zsandoz** [cdancy/bitbucket-rest#262]
We make use of `unapproveOnUpdate` boolean flag of repositories' pull request settings. When this Bitbucket feature is enabled, pushing new code to a PR automatically withdraws any previously existing approvals for that PR.

It [isn't mentioned in Atlassian's documentation](https://docs.atlassian.com/bitbucket-server/rest/7.10.0/bitbucket-rest.html#idp367) from what I can see, but it's a boolean in the top-level of a `PullRequestSettings`/`CreatePullRequestSettings` payload:

```
{
  "mergeConfig": {
    ...
  },
  ...,
  "unapproveOnUpdate": true
}
```

when doing a GET or POST to `/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/settings/pull-requests`.

Are you interested in adding support for this flag?

I'll submit a PR soon.

### Expected Behavior

`PullRequestSettings` and `CreatePullRequestSettings` have a field/parameter to get/set Bitbucket's `unapprovedOnUpdate` feature.

### Current Behavior

This flag isn't accessible via the existing API and API domain objects.

### Context

We would like to enable this flag every time we create a new repository.

**Comment by cdancy** [comment]
@zsandoz looking things over now...

**Comment by cdancy** [comment]
@zsandoz version `2.7.2` has been released with this change.

**Comment by zsandoz** [comment]
Great 😃 

Thanks very much

**Comment by cdancy** [comment]
yeah no problem and thanks for the PR.
________________________________
