### ISSUE TITLE
Repository + Project API not working 

### ISSUE THREAD

**Issue by cristinabuenahora** [cdancy/bitbucket-rest#280]
Hitting the Repository + Project API wasn't working whereas the BranchApi is. 

### Expected Behavior
Should return repositories / projects

### Current Behavior
Status code is 200 but there is an error on return. 

### Context
Can't actually hit either API
Seems related to this commit, both APIs that don't work have the path set to @Path("/rest/api/{jclouds.api-version}/projects") at the top level - https://github.com/cdancy/bitbucket-rest/commit/416c832f77922e79980e52213b7b0b3ae3d72b21

### Your Environment
Using the latest version

**Comment by cdancy** [comment]
@cristinabuenahora can you post a snippet of what you're doing, any logs you have gathered, and any http wire logs if you can hook things up?

**Comment by cristinabuenahora** [comment]
Yes, also I actually have a fix for this that is ready: https://github.com/cdancy/bitbucket-rest/pull/281
