### ISSUE TITLE
Support for liking a comment on pull requests

### ISSUE THREAD

**Issue by jutoft** [cdancy/bitbucket-rest#332]
Add api support for liking comments

### Expected Behavior

Add a likesApi() for pull requests that can
likeComment
getLikes for a comment
unlikeComment

### Current Behavior

There is no provided api for likes

### Context

We use likes to control special handling of pull requests, having official support would be great.
We currently have our own branch with support.

**Comment by jutoft** [comment]
> @jutoft this sounds like a great idea! Would you be interested in coding this up? I don't have the time at the moment and the library is pretty easy to use and wire something up.

I will create a pr with our internal fork of this project. Great that it is wanted.

**Comment by cdancy** [comment]
@jutoft I originally coded the core of the project but at this point it's largely community driven for any changes wanted. Feel free to send along whatever you have.
