### ISSUE TITLE
[Question] Is version 3.0.2 available?

### ISSUE THREAD

**Issue by fullben** [cdancy/bitbucket-rest#338]
Based on the state of this project (and as indicated by the [release notes](https://github.com/cdancy/bitbucket-rest/blob/master/RELEASE_NOTES.md)), I am under the impression that the most recent version of the library should be 3.0.2. Yet I seem to be unable to acquire this as a dependency.

### Expected Behavior
I should be able to use version 3.0.2 of this library as a dependency from maven central (as indicated by repo migration in 3.0.0).

### Current Behavior
I am only able to pull the library up to version 3.0.1

### Context
I am currently working on a project where I require access to an endpoint for which the implementation in 3.0.1 is broken (**project list**). Although not mentioned in the release notes for 3.0.2, this bug has been fixed for this version.

### Steps to Reproduce (for bugs)
Check [maven central](https://repo1.maven.org/maven2/io/github/cdancy/bitbucket-rest/) (only 1.0.0, 3.0.0, and 3.0.1 are available) or set up some basic project (e.g. Gradle) and populate the build file with something along the lines of
```groovy
plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.github.cdancy:bitbucket-rest:3.0.2'
}
```

**Comment by cdancy** [comment]
@fullben yeah I think you're right. Not sure what happened. Just pushed the release again now. Might take a few minutes to sync from sonatype but it should be good to go. Try again and let me know how things workout.

**Comment by fullben** [comment]
@cdancy looks good on my end now. Thank you so much for the quick fix! :)

**Comment by cdancy** [comment]
@fullben yeah no problem and thanks for reaching out. I suspect others did the same, seen it didn't work, threw their hands up, and moved on to something else.
