### ISSUE TITLE
Support new comments API: CommentThread

### ISSUE THREAD

**Issue by tomasbjerre** [cdancy/bitbucket-rest#38]
Bitbucket Server deprecated the comments API and will introduce CommentThread in version 5.

https://developer.atlassian.com/bitbucket/server/docs/latest/reference/api-changelog.html#Bitbucket_Server_4.13

I have not been able to find any documentation on the REST api for 5.0.

**Comment by cdancy** [comment]
@tomasbjerre good catch! Yeah doing a simple search I was not able to find anything other than what you posted. I'll keep this issue open to remind myself to poke around more.

**Comment by tomasbjerre** [comment]
Little status update here.

I have access to the Early Access Program now. I did not notice any new endpoints about comments so I asked the support. They replied:
```
The REST endpoints have changed only slightly. We hope to put out and EAP in the coming weeks with updated documentation.

I've gone through the changes quickly to try and provide you with a summary.

The anchors will now always include a diffType field which for commit comment threads should always be COMMIT. Pull request comment threads will have it set to EFFECTIVE, COMMIT, or RANGE depending on the context in which the root comment was added.

Getting pull request comments now allows for diffType, fromHash and toHash query parameters which allows you to narrow down the scope of the comments you are retrieving.

Streaming pull request changes now allows for a changeScope of ALL, RANGE or UNREVIEWED, as well as sinceId and untilId parameters. These are all mechanism to define the scope of the changes to stream (which also helps us narrow down the comment counts which will be attached to the changes). Similarly, streaming pull request diffs has added diffType, sinceId and untilId for the same reasons.

Hope this helps you test your integrations with our REST API until we can make the documentation available to you.
```

I'll try to find some time to test this soon.

**Comment by tomasbjerre** [comment]
https://confluence.atlassian.com/bitbucketserver/bitbucket-server-5-0-release-notes-889528342.html

**Comment by cdancy** [comment]
Closing as this is an older issue. If folks from the community want to help out and put together a PR I'd be more than happy to review.
