### ISSUE TITLE
How can I list all the Pull Request of a specific project

### ISSUE THREAD

**Issue by fenoloco** [cdancy/bitbucket-rest#39]
Hi, 
I was trying to build a tool to help me to detect open pull request and automatically advise each of the repository leads.

I reviewed the API and the code and I could find that implementation, can you guide me to the solution?

**Comment by cdancy** [comment]
@fenoloco currently there is no way through the API to search for PullRequests and sort based on say project name. What you can do is used the [PullRequests endpoint](https://developer.atlassian.com/static/rest/bitbucket-server/latest/bitbucket-rest.html#idm45295356811808), which is paged, and collect all available PullRequests and then search through them and sort them on your end.

This endpoint however is not currently coded in this library but I have it on the backlog to do so. As I was just about to release a new version of this library this coming weekend I can wire things together if you think it will help you. Let me know. Thanks.

**Comment by cdancy** [comment]
Sorry I was drawing a blank above and thought you were referring to "branch" instead of "project". Yes this is possible and is what I noted above that needs to be coded. Let me know and I will wire this up before my next release this weekend.

**Comment by cdancy** [comment]
Code has been merged to master to list all PullRequests from a given project and repo. I assume you mean this as PullRequests are not tied to a given project but to a repo under that project. As I said I will be publishing a new release this weekend. Let me know if the below snippet makes sense.

```
        List<PullRequest> pullRequests = new ArrayList<>();

        Integer start = null;
        while (true) {
            PullRequestPage pullRequestPage = api.pullRequestApi().list(projectKey, repoKey, null, null, null, null, true, true, start, 10);
            if (pullRequestPage.errors().size() == 0) {
                pullRequests.addAll(pullRequestPage.values());
                start = pullRequestPage.nextPageStart();
                if (pullRequestPage.isLastPage()) {
                    break;
                }
                Thread.sleep(1000); // don't overload server
            } else {
                throw new RuntimeException(pullRequestPage.errors().get(0).toString());
            }
        }
```

If you actually needed to iterate over some projects, and all their repos, you could do so but might be a lot of network traffic depending on number of projects and repos.

**Comment by fenoloco** [comment]
Thanks for the response, code snipped looks good and will be useful for me.
Thanks in advance, Are snapshot on Jcenter?

**Comment by cdancy** [comment]
@fenoloco closing issue as new release `0.0.14` is out. Let me know how things work out for you.

**Comment by fenoloco** [comment]
Sorry for the delay, works like a charm.
I think version is 0.0.13 and not 0.0.14 
Thanks!
