### ISSUE TITLE
Make use of jclouds "request options" builder instead of using N number of QueryParams

### ISSUE THREAD

**Issue by cdancy** [cdancy/bitbucket-rest#54]
Should be done across the board and will be required for 1.0 release.

**Comment by adam-tylr** [comment]
@cdancy I see you closed this recently. Is this no longer on the road-map?

**Comment by cdancy** [comment]
@adam-tylr just haven't had the time to do so and the issue has been open for so long that I figured I'd close it for now. Though if you, or someone else, wants to have a go at things by all means I'll take any PR's you or the community has ;)

**Comment by adam-tylr** [comment]
@cdancy I've been trying to look into what it would take to do this but I'm not really sure how. I googled and searched through some jclouds docs but didn't find anything about a request options builder. Do you have any links to point me in the direction of what you had in mind?
