### ISSUE TITLE
Stash (and maybe Bitbucket) canMerge is false though no merge conflicts

### ISSUE THREAD

**Issue by cdancy** [cdancy/bitbucket-rest#56]
Tagging a few committers who may have seen this before: @tomasbjerre @j0nathan33 @Gawen-pjr @petehayes 

Hey Guys,

We've got an issue using Stash (last version made available) where when we hit the [merge](https://developer.atlassian.com/static/rest/bitbucket-server/latest/bitbucket-rest.html#idm45770029274656) endpoint we get a `canMerge = false` with no vetoes or exceptions returned back. Furthermore the PullRequest page shows, sometimes, that there are merge conflicts but then no files are shown to actually have conflicts. We generally solve this by running a `git prune` and `git gc` server side though this only gets us by for a few weeks before we have to do it again. Atlassian suggests the same and also to upgrade to latest version of Bitbucket but we can't exactly do so at the moment. 

Anyone seen this before and have any recommendations one way or another? Searching the internets is not turning up anything useful. We're scratching our heads trying to figure out why this is popping over and over again. Any help is greatly appreciated.

Thanks,
Chris

**Comment by j0nathan33** [comment]
For us, we use bitbucket 4.12 and I don't see your error. Each time I send request to api, I receive all vetoes if branch can't merge.

**Comment by cdancy** [comment]
@j0nathan33 current speculation is that the size of our branch, and the number of open PullRequests, is playing into our problem. Because we have a multi-gigabyte repo, with say on average 30 open PullRequests, each call to the `merge` endpoint (which we poll through our testing process) we think might be bringing the instance to its knees. Just not entirely sure what goes on behind the scenes when one makes that call.
