### ISSUE TITLE
maven published artifacts have pom.xml depencies marked with `runtime` scope instead of `compile`

### ISSUE THREAD

**Issue by vasilievip** [cdancy/bitbucket-rest#73]
https://dl.bintray.com/cdancy/java-libraries/com/cdancy/bitbucket-rest/0.0.15/:bitbucket-rest-0.0.15.pom

```
    <dependency>
      <groupId>org.apache.jclouds</groupId>
      <artifactId>jclouds-core</artifactId>
      <version>2.0.1</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.google.auto.service</groupId>
      <artifactId>auto-service</artifactId>
      <version>1.0-rc3</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.google.auto.value</groupId>
      <artifactId>auto-value</artifactId>
      <version>1.3</version>
      <scope>runtime</scope>
    </dependency>
```

Related issue https://github.com/Netflix/Hystrix/pull/944/files

**Comment by cdancy** [comment]
@vasilievip this is interesting. I would expect then for all the use-cases we have here for this to pop seeing as how we are not defining these additional dependencies at runtime. Now I'm not entirely sure how things are working. Perhaps this is a maven only issue? We use gradle across the board here and have never had any issues. I've also never heard from anyone using this library that it's a problem.

But you're correct and I can reproduce locally so we should do something about it. Looks like there is a [working solution on this ISSUE](https://github.com/Netflix/dyno/issues/138) (which I found digging through the one you posted) by using a nebula plugin. Care to send in a PR to address this?

**Comment by vasilievip** [comment]
> Care to send in a PR to address this?

Nope. To be honest - I don't really like gradle, I'm using maven and do not want to mess with "copy-paste from stackoverflow" style of fixing build issues :).
 I reported issue for you to be aware of...

> I've also never heard from anyone using this library that it's a problem

They just adding deps w/o transitive dependencies resolution

**Comment by cdancy** [comment]
> Nope. To be honest - I don't really like gradle

Haven't drunk the kool-aid yet? ;) I was in your boat for a while until I finally saw the light, and lots of magic, of gradle especially coming from the rigid world of maven (though at times I do miss the rigidity of maven as it kept things simple at the sacrifice of functionality).

Let me see what I can whip together.
