### ISSUE TITLE
Junit Failing on DefaultReviewers when upgrade to Bitbucket 5.1

### ISSUE THREAD

**Issue by j0nathan33** [cdancy/bitbucket-rest#93]
After upgrade my local setup to bitbucket 5.1, integration test don't working anymore for defaultReviewers. I will try to fix today or tomorrow before I going to vacancy

**Comment by cdancy** [comment]
@j0nathan33 can you post the stacktrace here and/or what popped? Tests ran fine for me.

**Comment by j0nathan33** [comment]
StackTrace : 

> java.lang.NullPointerException
> 	at com.cdancy.bitbucket.rest.features.DefaultReviewersApiLiveTest.validCondition(DefaultReviewersApiLiveTest.java:167)
> 	at com.cdancy.bitbucket.rest.features.DefaultReviewersApiLiveTest.testCreateCondition(DefaultReviewersApiLiveTest.java:69)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
> 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
> 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
> 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
> 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
> 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
> 	at org.testng.TestRunner.privateRun(TestRunner.java:744)
> 	at org.testng.TestRunner.run(TestRunner.java:602)
> 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
> 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
> 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
> 	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
> 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
> 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
> 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
> 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
> 	at org.testng.TestNG.runSuites(TestNG.java:1144)
> 	at org.testng.TestNG.run(TestNG.java:1115)
> 	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:129)
> 	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:88)
> 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
> 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
> 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
> 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
> 	at com.sun.proxy.$Proxy2.stop(Unknown Source)
> 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:120)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
> 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
> 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
> 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
> 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
> 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
> 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)

Response : 
{
    "id": 3,
    "scope": {
      "type": "REPOSITORY",
      "resourceId": 10
    },
    "sourceRefMatcher": {
      "active": true,
      "id": "ANY_REF_MATCHER_ID",
      "displayId": "ANY_REF_MATCHER_ID",
      "type": {
        "id": "ANY_REF",
        "name": "Any branch"
      }
    },
    "targetRefMatcher": {
      "active": true,
      "id": "ANY_REF_MATCHER_ID",
      "displayId": "ANY_REF_MATCHER_ID",
      "type": {
        "id": "ANY_REF",
        "name": "Any branch"
      }
    },
    "reviewers": [
      {
        "name": "root",
        "emailAddress": "root@root.com",
        "id": 1,
        "displayName": "root",
        "active": true,
        "slug": "root",
        "type": "NORMAL",
        "links": {
          "self": [
            {
              "href": "http://192.168.99.100:32770/users/root"
            }
          ]
        }
      }
    ],
    "requiredApprovals": 1
  }

**Comment by j0nathan33** [comment]
Do you run on bitbucket 5.1 (https://www.atlassian.com/blog/bitbucket/bitbucket-server-5-1-signed-commits-and-more?utm_source=product-announcement-email&utm_medium=email&utm_campaign=server_fy17_q4_server_bitbucket_bb-server-5.1_consideration_blog_na_na_1&jobid=102048451&subid=873411037)

**Comment by cdancy** [comment]
No we are running `v4.14.0`.

**Comment by cdancy** [comment]
Resolved per #94
